# By default, SwiftLint uses a set of sensible default rules you can adjust:
#opt_in_rules: # rule identifiers turned on by default to exclude from running
#  - colon
#  - comma
#  - control_statement
#  - indentation_width
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - Source/*/ExcludedFile.swift # Exclude files with a wildcard
analyzer_rules: # Rules run by `swiftlint analyze`
  - explicit_self
force_try:
  severity: warning # explicitly
line_length: 200
type_body_length:
  error: 500
file_length:
  error: 5000
type_name:
  allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
  min_length: # only min_length
    warning: 1
    error: 1 # only error
disabled_rules:
  - trailing_comma
